### ISSUE TITLE
Errors fix

### ISSUE THREAD

**Issue by LorenzoTettamanti** [Atluzka/account-gen-bot#13]
Do you stil need help to fix some errors? i would like to contribute in some way!

**Comment by Atluzka** [comment]
There shouldn't be any errors that I'd know of, but if you have any ideas u can lmk. I'm not regularly updating this source, so It could take time before i add new features, probably when I'm really bored. I might even not add the feature if i think its just useless or only a few people would use that feature. All suggestions are welcome though. Sorry for the late response, I'm not on github that often anymore.
