### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Hammadzaki71** [Atluzka/account-gen-bot#3]
this doesnot work please someone help me add me on discord hammad#0001 please i really need help and i really need slash discord gen bot please respond hammad#0001 my name
![image](https://github.com/Atluzka/account-gen-bot/assets/137609290/0c1fa64e-3a1a-4280-b778-c66fbf3915b1)
this is the issue please help me please

it says no file found named main.py :( is the code wrong :(

**Comment by Atluzka** [comment]
Problem has been solved.
