### ISSUE TITLE
Wont let me add stock to the other roles except free

### ISSUE THREAD

**Issue by Thundergolder** [Atluzka/account-gen-bot#9]
![image](https://github.com/Atluzka/account-gen-bot/assets/163891295/ff04c65f-0f88-4bc7-9429-a81dc94c26c8)
![image](https://github.com/Atluzka/account-gen-bot/assets/163891295/3eb9d9e8-800b-4803-9e56-2924ec6d4c6d)

It shows nothing is in the .txt file

**Comment by Thundergolder** [comment]
Im sorry, nvm... I got it to work after 4 hours lol... but then, how do you add more roles except jus free and premium?

**Comment by Atluzka** [comment]
To add more roles just copy and paste the format in config and change the name
